Update Maintainers Committee
dotnet-foundation/website pull request #1031
Opened 2021-11-10 03:43 UTC by Jadhielv

Closes #1022

![image](https://user-images.githubusercontent.com/24376900/141045865-ae68a69a-a78b-4ca3-a06b-33e79c29d2c9.png)

2021-11-10 18:46 UTC, rprouse approved these changes

2021-11-11 00:32 UTC, Arhell approved these changes

2021-11-11 10:14 UTC, Perksey requested changes

2021-11-11 10:14 UTC, Perksey commented on input/community/committeelist/maintainers.yaml
>  Meets: When..
```suggestion
Meets: Second Wednesday of every month at 16:00 ET / 21:00 UTC for up to one hour.
```

2021-11-11 13:50 UTC, Perksey approved these changes

2021-11-11 13:50 UTC, Jadhielv commented on input/community/committeelist/maintainers.yaml
>  Meets: When..
![image](https://user-images.githubusercontent.com/24376900/141309373-f50b63fe-be1c-4d4e-a48a-ebb1852860c9.png)

Done.

2021-11-11 17:55 UTC, merged