Create michael-dera.md
dotnet-foundation/website pull request #1036
Opened 2021-11-17 18:58 UTC by michaeldera

Adding speaker information.

2021-11-17 18:58 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=1036) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=1036) before we can accept your contribution.<br/><br/>:x: michaeldera [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=1036)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=1036) it.</sub>

2021-11-17 19:57 UTC, rprouse requested changes
Other than that, looks good.

2021-11-17 19:57 UTC, rprouse commented on input/community/speakers/michael-dera.md
> +Pronouns: He
Build failure, Preferred gender pronouns should be of the form [subject]/[object] in lowercase (I.e. "they/them") (ValidateSpeakerPronouns)

2021-11-18 00:53 UTC, Arhell approved these changes

2021-11-23 03:31 UTC, rprouse commented
Still waiting on the pronoun fix @michaeldera

2021-11-27 22:53 UTC, rprouse approved these changes
![](https://media1.giphy.com/media/30pjt9I0SDs7R4ghlp/giphy.gif)

2021-11-27 22:53 UTC, merged