Add XAML Llama to Speaker directory 🦙
dotnet-foundation/website pull request #400
Opened 2020-10-13 22:58 UTC by michael-hawker

2020-10-14 01:51 UTC, shawnwildermuth requested changes
Please use your real name and we can't have non-standard tags (remove the XAML one).

2020-10-14 18:00 UTC, michael-hawker commented
@shawnwildermuth that better?

2020-10-15 08:43 UTC, Arhell approved these changes

2020-11-25 21:31 UTC, MaximRouiller commented
@shawnwildermuth I think that the changes you requested were actually done. I think we're good to merge.

2020-11-25 21:52 UTC, merged