Create george-chang.md
dotnet-foundation/website pull request #691
Opened 2020-12-15 16:15 UTC by georgechang

2020-12-15 16:15 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=691) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=691) before we can accept your contribution.<br/><br/>:x: georgechang [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=691)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=691) it.</sub>

2020-12-15 22:15 UTC, shawnwildermuth requested changes
Please enter in a short bio in your pull request. Once you do that, we can add you to the list.

2020-12-16 01:28 UTC, Arhell approved these changes

2020-12-16 01:41 UTC, shawnwildermuth approved these changes

2020-12-16 01:41 UTC, georgechang commented
> Please enter in a short bio in your pull request. Once you do that, we can add you to the list.

Done - thanks @shawnwildermuth!

2020-12-16 01:52 UTC, merged