Add new speaker profile for Abhishek Siddhu
dotnet-foundation/website pull request #703
Opened 2020-12-16 07:37 UTC by abhisheksiddhu

2020-12-16 07:37 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=703) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=703) before we can accept your contribution.<br/><br/>:x: abhisheksiddhu [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=703)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=703) it.</sub>

2020-12-16 23:52 UTC, shawnwildermuth requested changes
Please include a bio.

2020-12-17 01:10 UTC, Arhell approved these changes

2020-12-18 07:25 UTC, abhisheksiddhu commented
> Please include a bio.

I have added the bio.

2020-12-18 08:14 UTC, shawnwildermuth approved these changes

2020-12-18 08:14 UTC, merged