Create james-yeung.md
dotnet-foundation/website pull request #734
Opened 2021-01-29 16:13 UTC by ElderJames

2021-01-30 00:11 UTC, Arhell approved these changes

2021-02-02 23:08 UTC, shawnwildermuth requested changes
Please change Pronouns to be of the form of "he/his" or "she/her" or "they/they"

2021-02-03 03:20 UTC, ElderJames commented
Hi, @shawnwildermuth . I have fixed it.

2021-02-03 07:23 UTC, shawnwildermuth approved these changes

2021-02-03 07:24 UTC, merged