Create boguslaw-blonski.md
dotnet-foundation/website pull request #765
Opened 2021-02-19 21:05 UTC by filipoff2

2021-02-19 21:06 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=765) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=765) before we can accept your contribution.<br/><br/>:x: filipoff2 [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=765)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=765) it.</sub>

2021-02-23 23:13 UTC, shawnwildermuth requested changes
Please specify 'he/him', 'they/they' or 'she/her' for your pronouns.

Also, please include a biography at the bottom of the entry.

2021-02-27 07:50 UTC, Arhell approved these changes

2021-02-27 14:25 UTC, shawnwildermuth requested changes
Please change pronouns to lower case and separate with a slash (/)

2021-03-01 18:07 UTC, shawnwildermuth approved these changes

2021-03-01 18:07 UTC, merged