Added a profile for Lee Richardson (myself)
dotnet-foundation/website pull request #777
Opened 2021-02-22 14:50 UTC by lprichar

2021-02-22 14:50 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=777) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=777) before we can accept your contribution.<br/><br/>:x: lprichar [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=777)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=777) it.</sub>

2021-02-23 23:16 UTC, shawnwildermuth requested changes
Please change links to your blog to be https.

2021-02-23 23:24 UTC, lprichar commented
✔

2021-02-24 00:20 UTC, Arhell approved these changes

2021-02-24 00:34 UTC, shawnwildermuth approved these changes

2021-02-24 00:35 UTC, merged