Create sean-stride.md
dotnet-foundation/website pull request #780
Opened 2021-02-22 16:30 UTC by seanstride

2021-02-23 23:18 UTC, shawnwildermuth requested changes
Please add a bio at the bottom of the entry.

2021-02-24 00:20 UTC, Arhell approved these changes

2021-02-24 17:02 UTC, seanstride commented
@shawnwildermuth, I have now added a bio section

2021-02-24 21:34 UTC, shawnwildermuth approved these changes

2021-02-24 21:34 UTC, merged