Add charles-nurse.md to speaker directory
dotnet-foundation/website pull request #783
Opened 2021-02-22 18:12 UTC by cnurse

Submitting my application to be included in speaker directory

2021-02-22 18:12 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=783) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=783) before we can accept your contribution.<br/><br/>:x: cnurse [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=783)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=783) it.</sub>

2021-02-23 23:19 UTC, shawnwildermuth requested changes
Please change to use https on all links.

2021-02-27 07:50 UTC, Arhell approved these changes

2021-03-05 21:15 UTC, shawnwildermuth commented
Any word on making these changes?

2021-07-08 13:12 UTC, SeanKilleen commented on input/community/speakers/charles-nurse.md
> +He has spoken at many major conferences including the Software Developers Conference (SDC) (www.sdc.nl),   DevConnections (www.devconnections.com),  DevTeach (www.devteach.com), VSLive (www.vslive.co
```suggestion
He has spoken at many major conferences including the Software Developers Conference (SDC) (https://www.sdc.nl),   DevConnections (https://www.devconnections.com),  DevTeach (https://www.devteach.com), VSLive (https://www.vslive.com), Prairie DevCon(https://www.prairiedevcon.com) and DevReach (https://www.DevReach.com).    He is a frequent speaker at local User Groups and Code Camps, including .NET BC, VBug, Vancouver TechFest and Microsoft Developer days.
```

Adding https links as requested. @cnurse, if you accept these suggestions, that should validate this PR I think and allow it to be merged.

2021-07-12 21:20 UTC, merged