Create S Ravi Kumar Speaker Profile
dotnet-foundation/website pull request #785
Opened 2021-02-23 07:05 UTC by techierathore

Please add my profile to global Speaker list.

2021-02-23 07:05 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=785) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=785) before we can accept your contribution.<br/><br/>:x: techierathore [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=785)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=785) it.</sub>

2021-02-23 23:21 UTC, shawnwildermuth requested changes
Please change "Him/His" to "him/his" - must be lowercase.

Also, please change all links to use https

2021-02-24 01:55 UTC, techierathore commented
@shawnwildermuth thanks for your comments, updated the file according to them. Let me know if any more changes required.

2021-02-24 05:56 UTC, shawnwildermuth approved these changes

2021-02-24 05:57 UTC, merged