Create eric-potter.md
dotnet-foundation/website pull request #789
Opened 2021-02-23 13:02 UTC by pottereric

2021-02-23 13:03 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=789) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=789) before we can accept your contribution.<br/><br/>:x: pottereric [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=789)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=789) it.</sub>

2021-02-23 23:23 UTC, shawnwildermuth approved these changes
If possible, please change links to use https.

2021-02-23 23:23 UTC, shawnwildermuth requested changes
Sorry, please change links to use https if possible.

2021-02-24 00:33 UTC, shawnwildermuth approved these changes

2021-02-24 00:33 UTC, merged