Adding Ashirwad Satapathi in the Speaker Directory
dotnet-foundation/website pull request #833
Opened 2021-03-26 13:54 UTC by AshirwadSatapathi

2021-03-26 13:55 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=833) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=833) before we can accept your contribution.<br/><br/>:x: AshirwadSatapathi [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=833)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=833) it.</sub>

2021-03-27 09:12 UTC, Arhell approved these changes

2021-04-03 04:52 UTC, shawnwildermuth requested changes
Pronouns should be noun/object (e.g. they/they in your case). Please change.

2021-06-13 07:47 UTC, shawnwildermuth approved these changes

2021-06-13 07:47 UTC, merged