Update _current-newsletter-draft.md
dotnet-foundation/website pull request #853
Opened 2021-04-23 16:11 UTC by isaacrlevin

2021-04-23 16:50 UTC, BethMassi requested changes
Made some suggested changes

2021-04-23 16:50 UTC, BethMassi commented on input/blog/posts/_current-newsletter-draft.md
> +https://dotnetfoundation.org/projects/spotlight?project=Orleans
```suggestion
[Orleans](https://dotnetfoundation.org/projects/spotlight?project=Orleans)
```

2021-04-23 16:50 UTC, BethMassi commented on input/blog/posts/_current-newsletter-draft.md
> +https://dotnetfoundation.org/projects/spotlight?project=Roslyn
```suggestion
[Roslyn](https://dotnetfoundation.org/projects/spotlight?project=Roslyn)
```

2021-04-23 16:50 UTC, BethMassi commented on input/blog/posts/_current-newsletter-draft.md
> +For March, .NET Foundation Marketing Committee member, Isaac Levin, spoke with Maintainer of the Orleans prject, Reuben Bond, to talk about the work Microsoft is doing in the Microservices space with
```suggestion
In March, .NET Foundation Marketing Committee member, Isaac Levin, spoke with Maintainer of the Orleans project, Reuben Bond, to talk about the work Microsoft is doing in the Microservices space with .NET.
```

2021-04-23 16:50 UTC, BethMassi commented on input/blog/posts/_current-newsletter-draft.md
> +For April, Isaac spoke with Maintainer of the Roslyn Compiler prject, Jared Parsons, and gave a little insight into how Microsoft thinks about building compilers and other language tools.
```suggestion
In April, Isaac spoke with Maintainer of the Roslyn Compiler project, Jared Parsons, and gave a little insight into how Microsoft thinks about building compilers and other language tools.
```

2021-04-23 16:50 UTC, BethMassi commented on input/blog/posts/_current-newsletter-draft.md
> +Roslyn is the C# and Visual Basic Compiler and IDE experience project. It contains the source code for all of your C# and VB experience all the way from the core compilers, Intellisense, syntax highl
```suggestion
Roslyn is the C# and Visual Basic compiler and IDE experience project. It contains the source code for all of your C# and VB experiences all the way from the core compilers, Intellisense, syntax highlighting, and edit and continue logic. Anything you want to know about how your development environment works for .NET you can see in action in this repository.
```

2021-04-25 09:01 UTC, Arhell approved these changes

2021-04-28 22:30 UTC, BethMassi approved these changes

2021-04-28 22:30 UTC, merged