Create suresh-dasari.md
dotnet-foundation/website pull request #854
Opened 2021-04-26 16:54 UTC by tutlane

2021-04-26 16:54 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=854) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=854) before we can accept your contribution.<br/><br/>:x: tutlane [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=854)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=854) it.</sub>

2021-04-26 19:42 UTC, shawnwildermuth approved these changes

2021-04-27 07:17 UTC, Arhell approved these changes

2021-04-27 07:25 UTC, shawnwildermuth requested changes
Nuget isn't a valid topic. Please remove.

2021-04-27 08:19 UTC, tutlane commented
> Nuget isn't a valid topic. Please remove.

Removed the topic. Please check and approve the pull request

2021-04-27 09:10 UTC, shawnwildermuth approved these changes

2021-04-27 09:19 UTC, merged