Update suresh-dasari.md
dotnet-foundation/website pull request #855
Opened 2021-04-27 16:12 UTC by tutlane

Added feed and other details.

2021-04-27 21:27 UTC, shawnwildermuth requested changes
We don't support creating sections. Please just include your bio not a list of tutorials.

2021-04-28 00:18 UTC, Arhell approved these changes

2021-04-28 02:40 UTC, tutlane commented
> We don't support creating sections. Please just include your bio not a list of tutorials.

Updated content as per the comments, please check it and approve.

2021-04-28 04:41 UTC, shawnwildermuth approved these changes

2021-04-28 04:41 UTC, merged