Create samuel-adranyi.md
dotnet-foundation/website pull request #875
Opened 2021-05-31 17:23 UTC by sadranyi

2021-05-31 17:23 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=875) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=875) before we can accept your contribution.<br/><br/>:x: sadranyi [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=875)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=875) it.</sub>

2021-06-01 00:09 UTC, Arhell approved these changes

2021-06-01 21:11 UTC, shawnwildermuth requested changes
Please change the case of "He/Him" to "he/him".

2021-06-02 02:35 UTC, shawnwildermuth approved these changes

2021-06-02 02:44 UTC, merged