Create Jamesmillar.md
dotnet-foundation/website pull request #967
Opened 2021-09-02 15:43 UTC by Distinctlyminty

2021-09-02 15:43 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=967) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=967) before we can accept your contribution.<br/><br/>:x: Distinctlyminty [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=967)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=967) it.</sub>

2021-09-02 20:44 UTC, shawnwildermuth requested changes
Please remove the "ask me about mentoring". We'd rather just have your qualifications/background. Also, please remove the duplicate info links on the bottom (you can include ones that aren't already included on top).

2021-09-02 20:56 UTC, shawnwildermuth approved these changes

2021-09-03 00:08 UTC, Arhell approved these changes

2021-09-03 04:12 UTC, shawnwildermuth requested changes
Sorry, last change. The pronouns need to be lowercase.

2021-09-03 07:45 UTC, shawnwildermuth approved these changes

2021-09-06 08:20 UTC, merged